// <auto-generated />
using System;
using DotnetStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220108090828_UpdateUserAddress")]
    partial class UpdateUserAddress
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DotnetStore.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("DotnetStore.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DotnetStore.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15e49d1d-038e-43da-8627-10c78caa560c"),
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("2c8352ad-dff6-49ca-9acd-213aa2a4806e"),
                            Name = "Åland Islands"
                        },
                        new
                        {
                            Id = new Guid("10cbebc8-c147-4c05-afea-61cafcfd730c"),
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("8240b953-5e0b-4420-b2ea-eb97392302e2"),
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = new Guid("7a8ccc2b-accd-490d-8c05-ec308d3dc402"),
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("d3aba647-b467-4cf9-a47d-db77b4f6aa92"),
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("47b21c5c-3e46-4127-8e76-1367bd9b986e"),
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = new Guid("380a6fe5-e8ed-4813-b986-2b75284c76c7"),
                            Name = "Antigua & Barbuda"
                        },
                        new
                        {
                            Id = new Guid("bf6d91b8-e360-4374-903e-34a7db3b750c"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("02806a00-729b-4f7c-bbb8-5fd5469f03eb"),
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("681af4c1-d201-46f6-98c9-7f65b5e6ce4f"),
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = new Guid("dab76331-8ee0-4cb3-9ad0-fbcf89c4d599"),
                            Name = "Ascension Island"
                        },
                        new
                        {
                            Id = new Guid("d937de63-deac-4cd4-99d3-e3ce31cdc957"),
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("069f0d15-84bb-459a-833b-7c6784de5870"),
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("53d47c74-0b23-4bd7-b4bd-e5754e8e38aa"),
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("9610cd35-9e04-416b-8921-1081306c5223"),
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("6e76a297-ad54-4435-b02c-0ef3f52b4115"),
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = new Guid("f8cc2196-9615-4a24-af3e-56db88d9afed"),
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("4312738f-6044-4834-bb67-1f03aaf0cf89"),
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("7e5e67d3-ec47-412b-b697-15431eec3b8a"),
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = new Guid("e83d0999-6440-4978-82b1-3b3c59311c64"),
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("a60e7b97-88f7-4f4e-94ff-4eb96bf0bb48"),
                            Name = "Belize"
                        },
                        new
                        {
                            Id = new Guid("3f3fa48d-6453-401a-98f3-a6cbac581813"),
                            Name = "Benin"
                        },
                        new
                        {
                            Id = new Guid("025600ed-62b5-44eb-af29-f14a85f532aa"),
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = new Guid("f43a17c1-8c26-48f4-980c-c564460d7861"),
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = new Guid("b0c5af6f-a81f-4f45-9a9c-7221f38ed362"),
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("125c20d3-2d0c-4cc9-9310-d258a695c706"),
                            Name = "Bosnia & Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("62d95e5f-ca14-4ee8-aad5-4d7d60a2435d"),
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = new Guid("a2f05e3f-4a82-4d41-ac69-9b52a326d4ce"),
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("63de1067-e41f-410b-b515-aa9a92ced755"),
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = new Guid("98d3508c-4052-4fa0-ad59-bbdd91f37387"),
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            Id = new Guid("c0a725c4-09c8-482a-9a1b-e3b6a4de6a03"),
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = new Guid("99cd8388-0559-4db5-8505-849e6f451c90"),
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("445cb781-2731-4eb2-b499-708c9ac481f6"),
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("886ca75f-906f-40c1-ac1f-cf3ddbba50af"),
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("3d63db52-d59e-4770-93bd-f30ec66e49e7"),
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = new Guid("60ee4b13-7ecc-40c5-a518-6605e9ccdf96"),
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = new Guid("48011cfb-d470-4ff4-b2bd-6a3309834223"),
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("08a96264-cce4-4629-a552-eff5a5e9d40e"),
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = new Guid("f3d87df4-5119-4441-aef1-daf64950c2ef"),
                            Name = "Caribbean Netherlands"
                        },
                        new
                        {
                            Id = new Guid("ef1e1178-32f3-4298-a24c-07bfabd00ec0"),
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = new Guid("ff7ef791-e19a-4263-90ea-041d70199b1b"),
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = new Guid("ee69d820-e73d-4bfe-bffb-f42345e8cf73"),
                            Name = "Chad"
                        },
                        new
                        {
                            Id = new Guid("6813d671-debb-453a-b84e-607f2870fbeb"),
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("e63d3403-000c-4fb7-80df-1574a07c5824"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("66d74c46-4ebc-4134-8f8b-7415af64b9f5"),
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = new Guid("a4be848b-9d02-4693-8be6-6c84a938e72b"),
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = new Guid("9f903477-39a8-4070-b3cc-3b34366965cf"),
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("eafde7a7-4cbf-4d5f-badb-786d6ca81eb5"),
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = new Guid("92824691-ae1b-41cd-a264-92e5173d282d"),
                            Name = "Congo - Brazzaville"
                        },
                        new
                        {
                            Id = new Guid("46d6ac30-7974-4529-a41b-6a39dc5a869b"),
                            Name = "Congo - Kinshasa"
                        },
                        new
                        {
                            Id = new Guid("875997d1-a0a0-4d81-a263-8b7d6aa62e9c"),
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = new Guid("30b1294d-f0b5-4213-bfe8-bb325eca0c0a"),
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("c5b68f72-364b-4c9c-acae-054d033146a3"),
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("94a43670-e8f9-49af-b845-58ebbb285b18"),
                            Name = "Curaçao"
                        },
                        new
                        {
                            Id = new Guid("afcab471-de0d-4e76-9435-e38b31d1ce6f"),
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = new Guid("add51629-54c3-4b14-ba30-03349d516bc8"),
                            Name = "Czechia"
                        },
                        new
                        {
                            Id = new Guid("70295464-e7b1-43b1-9ae6-daebc0cf5483"),
                            Name = "Côte d’Ivoire"
                        },
                        new
                        {
                            Id = new Guid("c20eab08-b456-46ee-97b2-ec61fe6f4755"),
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("9d3b3c71-9fcd-4b93-a10e-9d247b1e45ff"),
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("c0952855-f416-4175-882a-b81146628d6c"),
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("55cb37aa-3e12-4590-820d-87984f58291f"),
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = new Guid("05e8dd92-248f-4959-952b-103dda61e630"),
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("7918d280-b4e8-435c-9611-00fde585e44c"),
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("9d882d15-090a-4868-bd1b-cb69fea58468"),
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("3675bd7d-996c-450e-887a-612418dcff36"),
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = new Guid("eaa1f576-b58c-4410-b23c-ef41f90082b7"),
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("2a58ace7-76e0-45f1-9b92-556fd4ecbf49"),
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("da4175c4-63e8-4221-9344-b2a6cf4eedef"),
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = new Guid("449608a3-7fe7-47cf-89d9-c51a9a3415bc"),
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = new Guid("a8067641-89c5-461e-8633-e92046f586f6"),
                            Name = "Falkland Islands"
                        },
                        new
                        {
                            Id = new Guid("c57cefea-3915-4908-a672-f9a306b89ef5"),
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = new Guid("301f7ded-2043-44f0-b543-bd05db290e17"),
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("e77b5130-e6a5-41bd-be0c-e3aa94f2d3bd"),
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("e66a3ea3-a6eb-448a-a64a-42d8b61776f4"),
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("4972d29d-a0ea-4802-9fea-3b65f8b9762b"),
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = new Guid("d849e7e2-8072-4e4e-bc0e-b616d3ae2c14"),
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = new Guid("207bf724-c538-45c9-a505-9ff1eb237dbf"),
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = new Guid("ab313110-b772-48a4-9683-d4f002f7f8ef"),
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = new Guid("b5587b1f-e9e3-47eb-a3f4-ff06b446c75f"),
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("a7380c98-1eea-4921-b17d-c9a7779268b6"),
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("c6ad0fe1-1f7f-454e-9638-37337fae464a"),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("d91f6cd3-9069-4142-8a5d-7399c3154e6d"),
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("b5141774-335b-439d-9735-e48e9ff3c95b"),
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = new Guid("b0d322ad-b7bf-4d1c-9fa2-53633308f3e3"),
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("25e08a1e-98ec-45c5-b40e-87e6ba01adee"),
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = new Guid("b3919833-6ce0-42e0-a660-0f9d6ffcd4de"),
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = new Guid("39beea01-9e4f-49a2-8de1-56c6ae8cbc91"),
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = new Guid("f177a227-a317-4ad1-985a-b4558ef63f87"),
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("5e9c5bc5-6cbd-4fc9-9dae-85e81b66652a"),
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = new Guid("04023209-6df2-49e5-ae48-9e6e1df951f5"),
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("d8605f18-1fbb-4c1d-b10f-c18fdacaa509"),
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = new Guid("a5d4714e-3dc0-4d15-a649-77825f817245"),
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("5afcb2e0-8174-4b2c-b8c6-83c452566a14"),
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = new Guid("1a6a9420-88b3-4ff7-8100-94a9f99b071c"),
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("5090d4ba-0547-4fa0-8d06-6a9a6a2d19d9"),
                            Name = "Hong Kong SAR"
                        },
                        new
                        {
                            Id = new Guid("5e42b66e-b4e4-45d1-9141-e2ded33b0011"),
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("3c99bd2d-5557-49e1-bb5a-c38448e1a3f6"),
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = new Guid("9ef4cbd7-6af6-4073-b817-5d95f303e00d"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("1fa5a941-18ef-4ebd-af02-28a7bf7e661d"),
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("5b5adac9-da4d-43d0-8ea3-68cec73be9e7"),
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("91d2daf2-02f1-4b4d-9a8d-91ca914e862d"),
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("0461e96b-fe47-4daf-81e4-c1a7527eb311"),
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = new Guid("6c77e740-69b5-415f-b115-f4b82b162236"),
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("8ad83c0c-37a7-444a-a536-d855cc2fa24e"),
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("5feb115e-ea36-406a-85f1-457642f912e0"),
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("3528035a-ec9e-456a-a859-ebfdff2d908c"),
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("dbe30d2b-0ae3-46cb-a498-a1dfa8e7a100"),
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = new Guid("47f69504-b4aa-44cb-829d-35b0cd0e75b8"),
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = new Guid("da5ea1d1-a172-4e8a-8016-6b81d0f6f943"),
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = new Guid("a1536a0c-1ed4-41dc-be07-3e489e6d1597"),
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("0bd3cd87-8baa-4865-8382-bca43f61bf75"),
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("19161e30-fcfb-4706-a13a-ef06a16fc623"),
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = new Guid("5eb5f9fd-56e4-4844-b93a-b76210f56921"),
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("d6b61817-1d34-48c0-b468-4858ef5e03f0"),
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = new Guid("014866f2-3523-415f-9105-7e0e015c5831"),
                            Name = "Laos"
                        },
                        new
                        {
                            Id = new Guid("66cf07f9-fbf6-40d6-9465-51fa587a7224"),
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = new Guid("bcccbc47-c390-405d-bec6-9ea974aeace8"),
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = new Guid("14a73be9-bfe2-400f-9ac1-0067c37e74a9"),
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = new Guid("c7c91fd2-708a-45af-99bd-79da3e015127"),
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("2903fdad-e889-4e20-b919-33f7d33760df"),
                            Name = "Libya"
                        },
                        new
                        {
                            Id = new Guid("5a1ba888-a2cf-4c18-853a-52fa779d0297"),
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("a4b6ce44-aa0a-4198-8561-a8294ae01bd9"),
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = new Guid("a65d1906-b388-40e7-93b2-b93fedc60b98"),
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = new Guid("086d79e8-1186-493e-9763-3cee70c696af"),
                            Name = "Macao SAR"
                        },
                        new
                        {
                            Id = new Guid("ad748322-0882-43f9-abb2-b9167b378f81"),
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("3a241973-cdfb-4c58-ae27-88bc8cd101e2"),
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("904debfe-ef94-42e2-8e34-ae7b1dc76c67"),
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = new Guid("4823b221-b58a-4d18-89e3-042fa0bafd9d"),
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = new Guid("1174a8e2-4d4a-4049-b22c-2335add0e18e"),
                            Name = "Mali"
                        },
                        new
                        {
                            Id = new Guid("3cd72cc2-d5e1-4c34-a75e-078527b9b0cf"),
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("640b4f06-1523-44cd-8919-c6d8bb902ca7"),
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = new Guid("589a27e2-d88c-4745-8a0f-ca6149054130"),
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("7db81d34-6ed4-4296-940d-d6dd9fe79db6"),
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = new Guid("83d63755-206e-434e-ae5e-d0a4d35cdd2c"),
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = new Guid("468210ac-949e-4d22-9e9e-2c4ac13d5bb1"),
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("f17e51c8-4c7f-4594-bb89-7551e5c279a3"),
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = new Guid("84ebcc2b-e88d-45cc-9382-6b5ae3ee0295"),
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("27292543-9df6-476f-9ae5-3959865ef98a"),
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("7ae0d961-f828-4e28-a98a-4107fdc9817f"),
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("04c952d6-1479-44e8-a558-2a1f6ac5c3f6"),
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = new Guid("8bf0daf2-e8ed-4706-9388-b3d39d5b504d"),
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = new Guid("e3ada53d-7d18-484c-bf3f-9f15be0a4ce7"),
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("8fbba01f-0efd-4d26-a0d3-596da26c02c7"),
                            Name = "Myanmar (Burma)"
                        },
                        new
                        {
                            Id = new Guid("926aff6c-6daa-47f9-b617-517c0519f40e"),
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("cf0d1faf-a928-4723-8680-b0667a9521aa"),
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("1abf66db-6db9-4e3e-a9b0-05d9bdf341b0"),
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("42f151ef-394a-434b-a26f-ea498759d551"),
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("ded3e45d-ec1d-46e7-82dc-040e692d9d20"),
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = new Guid("97577fa0-fb5e-46e2-a028-e5b2df5616b7"),
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("0dff80b7-a3d3-4291-9d73-5dce8f4c6018"),
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("1fec259c-6d58-4103-80c8-34982bebd4bd"),
                            Name = "Niger"
                        },
                        new
                        {
                            Id = new Guid("ba03f42b-e332-443b-a3ae-4eebd0d06557"),
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("8aef24e1-1f09-4537-bf10-9d44ee254ede"),
                            Name = "Niue"
                        },
                        new
                        {
                            Id = new Guid("6c300e6a-e8f7-43b0-bfc8-4305df94f254"),
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = new Guid("c7aae039-a31f-4e4f-a32e-c90e8f8f0cf5"),
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = new Guid("c8b5c856-e642-4539-a849-9942fa6cde8d"),
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("cef93d51-7977-4b09-9495-161632b15c83"),
                            Name = "Oman"
                        },
                        new
                        {
                            Id = new Guid("f5965f40-c78a-4b5b-b2f9-1ec956a6cfde"),
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("c1a7a782-b976-4fa8-9dcb-39b653b7031a"),
                            Name = "Palestinian Territories"
                        },
                        new
                        {
                            Id = new Guid("0105c859-98e1-4029-8b74-c8e81a97bcc5"),
                            Name = "Panama"
                        },
                        new
                        {
                            Id = new Guid("7faae277-37c7-45ae-b100-a264ede95246"),
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = new Guid("55b7e162-23a0-4e8a-a96f-711e9ab5816c"),
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("d8ff7c47-7043-4ece-ab20-ec5fe1fd416d"),
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("034d38a5-bf52-4d65-b214-2ec312707e2a"),
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("b6b3326d-150d-41ad-a35e-312ee5166884"),
                            Name = "Pitcairn Islands"
                        },
                        new
                        {
                            Id = new Guid("ff7724ed-3e0a-4b69-b2e0-02440462d2e9"),
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("0d9249ff-2b7e-43cc-99ba-bcd44b1dec21"),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("0e4d9b6a-28eb-41a9-97e5-2822590f606d"),
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("ff61c8db-99cb-40d3-9bbb-44bbf850c59f"),
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = new Guid("c9af85d7-54a4-4008-9028-9fbfbbf27f4f"),
                            Name = "Romania"
                        },
                        new
                        {
                            Id = new Guid("36b02a8b-d063-4f38-8dcb-0dcb477527df"),
                            Name = "Russia"
                        },
                        new
                        {
                            Id = new Guid("3fad7a5a-c281-48f7-bda9-b2fabf9fb131"),
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = new Guid("d128d8ad-3452-42fa-a753-356c3cced105"),
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("481e3d83-9443-4640-b168-a369705fc395"),
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("5cb89149-42cd-4340-9677-967ddb748ee7"),
                            Name = "São Tomé & Príncipe"
                        },
                        new
                        {
                            Id = new Guid("094c20c0-1211-444d-80af-1a4f6797c262"),
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("444343d5-c9b6-46ef-b3a0-9031616ce99b"),
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("1bb32cf4-175a-48ca-8f25-2ec653591340"),
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("8a621621-8c14-41c4-a6f8-c904c0f4ddb3"),
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("b60b344d-87c1-46d4-a156-1293a4465211"),
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = new Guid("0178bccf-c6eb-410a-bfc1-60276cf98060"),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("1cf89f00-440e-4321-9443-257e9334562f"),
                            Name = "Sint Maarten"
                        },
                        new
                        {
                            Id = new Guid("502ed735-9b22-444a-a75b-248db5c31a0e"),
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = new Guid("4f7fa97d-307b-4efb-9137-de2b5d325ac7"),
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = new Guid("692e5fbf-8e22-4749-9eb3-ca99f3140055"),
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = new Guid("c9fde3ba-612a-4f87-a220-5cc144fa503e"),
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("d414361b-f440-4784-9e47-0e7c76a07685"),
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("06fc6d4d-1159-4f7e-9866-4d6be72f3f39"),
                            Name = "South Georgia & South Sandwich Islands"
                        },
                        new
                        {
                            Id = new Guid("a2bb13e8-af95-4cad-b5c6-8bfd57e2a376"),
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = new Guid("2a4edf5e-d69b-4e5e-959b-c2810c51367b"),
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = new Guid("656cb59f-5fc6-4cc8-aa13-b28eed4a7659"),
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("11e28313-3518-4acc-b573-f09b6ac99554"),
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("165ab59e-450c-4e66-83c3-2c90782dd52c"),
                            Name = "St. Barthélemy"
                        },
                        new
                        {
                            Id = new Guid("3aee44d6-51b5-449c-b72e-09f918469e26"),
                            Name = "St. Helena"
                        },
                        new
                        {
                            Id = new Guid("7e33920e-d2d9-40ac-8179-2ab6be84ba84"),
                            Name = "St. Kitts & Nevis"
                        },
                        new
                        {
                            Id = new Guid("dd2aed97-80f0-4598-8e84-09714fbb953c"),
                            Name = "St. Lucia"
                        },
                        new
                        {
                            Id = new Guid("5d0135e3-8431-41d4-932a-31ee89c336e0"),
                            Name = "St. Martin"
                        },
                        new
                        {
                            Id = new Guid("acdf75a3-ded0-4906-9587-e2f5a59075fd"),
                            Name = "St. Pierre & Miquelon"
                        },
                        new
                        {
                            Id = new Guid("97558596-2524-44a5-a99d-2022019ad78a"),
                            Name = "St. Vincent & Grenadines"
                        },
                        new
                        {
                            Id = new Guid("a7596fb2-5a02-4daf-b5e2-594369a408ff"),
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = new Guid("b8ad3105-3475-48c0-b256-99da186fbc1e"),
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = new Guid("74003ea9-40c6-44e1-92c4-172f7f776ac0"),
                            Name = "Svalbard & Jan Mayen"
                        },
                        new
                        {
                            Id = new Guid("8c7a25c4-ce40-45a2-881e-d66a9a1b63ef"),
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("af63246e-cec4-4ff0-b3d6-108aa6ebf7e2"),
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("054f4d0a-3959-4e90-bf69-f511d11467c9"),
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = new Guid("a77647f1-43bd-4986-92f5-07a442fb304a"),
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = new Guid("d0cb7396-f885-4603-88bf-3f63c67ffac1"),
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = new Guid("3c74eb84-86f2-4656-83d7-06b5f23c1074"),
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("55d1cf09-8602-4445-82d8-ccbcec581c68"),
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = new Guid("8a51288b-73c2-433b-88b5-194b9ba63b5a"),
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("18e06dcf-dba9-4437-9f88-a80d49d7983b"),
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = new Guid("71ae0093-d2d1-46b2-8af1-31bbc8f8bac3"),
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("6205190c-3901-4338-933e-fb7df58eb05b"),
                            Name = "Trinidad & Tobago"
                        },
                        new
                        {
                            Id = new Guid("7fd92310-705a-4ffd-88dd-b4de757e909c"),
                            Name = "Tristan da Cunha"
                        },
                        new
                        {
                            Id = new Guid("f67c79d5-fafd-4bd6-b17e-392355ac853e"),
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = new Guid("38f99c26-9a4c-4fc4-8f09-722440ebbf9b"),
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("7776d491-b3b4-446e-b778-6cff6c63a1cf"),
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = new Guid("c902fbec-1981-45c9-a7e8-9037d0b752d2"),
                            Name = "Turks & Caicos Islands"
                        },
                        new
                        {
                            Id = new Guid("ce2f8c52-c5ac-4f19-9018-cab9f979961e"),
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("133e855c-e776-426f-bf49-e153b9846925"),
                            Name = "U.S. Outlying Islands"
                        },
                        new
                        {
                            Id = new Guid("c8397662-795b-45d4-a553-32f2f64c0ad3"),
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("710d8540-9d81-47ed-8553-892c926f1752"),
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("a770f955-3363-4610-802b-38649888324f"),
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = new Guid("42b82586-8f9d-4574-be7d-f22a11cd1c8b"),
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("f800b9a5-8575-41a6-9edb-d26adcd2297c"),
                            Name = "United States"
                        },
                        new
                        {
                            Id = new Guid("17716b04-1f88-457e-a94c-4b0178d7adc9"),
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("a1cb6c2b-407f-4af7-aa1e-a3dade3668f1"),
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = new Guid("c1f2fbd3-942c-4279-a9f4-5133c772c6c5"),
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("78bf5006-1849-42ee-94d4-6e92772cb9a7"),
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = new Guid("07a37ddb-8838-4995-a029-29ebab0deff5"),
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("be6c3db6-82eb-4587-b567-35b1b19dd503"),
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = new Guid("5628e662-35a6-44f6-a8c8-6c69ce139169"),
                            Name = "Wallis & Futuna"
                        },
                        new
                        {
                            Id = new Guid("8246aef2-a939-446b-8e02-cb028a3b3db8"),
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = new Guid("da31b6be-9305-424b-99ab-7835c181493c"),
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("566afe6a-64cf-47a0-990d-0afb422004de"),
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("8afd6a2f-c81f-42c7-8f08-3398f463f761"),
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("DotnetStore.Models.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("DotnetStore.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DotnetStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DotnetStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("DotnetStore.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotnetStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DotnetStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
