// <auto-generated />
using System;
using DotnetStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220106225536_AddCountriesSeedData")]
    partial class AddCountriesSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DotnetStore.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("DotnetStore.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DotnetStore.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff104342-c211-4ce1-bba3-6607db0430fc"),
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("00c89937-c3cf-41de-8e8d-d043fa827d29"),
                            Name = "Åland Islands"
                        },
                        new
                        {
                            Id = new Guid("b371e846-abb6-44df-a15f-655bd7fce401"),
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("3733b688-858e-40ac-a4e8-efca9d738132"),
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = new Guid("e9f9cb1c-ce37-49e6-9a86-805adfd4d2c1"),
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("bf3bfc06-7486-43fc-b7e5-dd4c4ae5f474"),
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("675336ca-40c5-4135-85a5-f252dbeeba6e"),
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = new Guid("6a04cb70-676b-4d9b-9765-8ee3815ab599"),
                            Name = "Antigua & Barbuda"
                        },
                        new
                        {
                            Id = new Guid("17c301b8-9bc1-4220-8947-6eb9fd7f405f"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("dc509335-e9c1-4162-9130-105286b2e9ef"),
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("43a25128-9e78-41ba-ba20-a7f2ab9f6be7"),
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = new Guid("8f3e7de8-deee-47ec-9916-7d28fd0e78a7"),
                            Name = "Ascension Island"
                        },
                        new
                        {
                            Id = new Guid("146d9945-2c69-477b-9950-9b6d1c109a32"),
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("64a7009f-88c3-42b9-8b14-07543fc0f1c9"),
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("6205b2af-2d51-4ec5-bef0-701338d4a83d"),
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("ab23ca55-721b-4e13-9378-c68444e8410c"),
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("e8a904a1-3a69-4ee9-aad5-cab984a9868d"),
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = new Guid("70cfcf8c-a36e-4dd8-8e35-b3e1997711ae"),
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("1ea610ce-91cc-4379-a8ae-7bba6c9c16c3"),
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("520f9813-184c-4292-ae69-bec5746dd93e"),
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = new Guid("4730724a-af67-4276-a19f-de2e50b7cfcf"),
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("963f5d46-f303-4e90-85cd-586268d00bbc"),
                            Name = "Belize"
                        },
                        new
                        {
                            Id = new Guid("0e7689e6-da83-4bcf-9683-1be70d2c30a6"),
                            Name = "Benin"
                        },
                        new
                        {
                            Id = new Guid("050f5dd7-f49c-4e30-b633-9e92fe632156"),
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = new Guid("e7fe6218-4e75-441c-94c3-20c595b5d76a"),
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = new Guid("cc49a050-3961-4ab9-90a3-c1e78e785f2e"),
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("2f049628-c23e-4cd0-95df-5de0524aef0c"),
                            Name = "Bosnia & Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("c611af37-7533-41a0-9818-d8422c32d6ec"),
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = new Guid("14b83869-c01c-4d1f-85ba-9bacdf22f3bb"),
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("4048f6c8-f734-4600-87e7-f7cf4399f2c9"),
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = new Guid("b39ffe31-dd69-4f0b-b94a-16d5cadb456b"),
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            Id = new Guid("10d7c30e-813e-4307-89be-cfab52fff2af"),
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = new Guid("e302c62c-48f5-4224-932a-5d76401fd3d1"),
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("fcd814b4-38d9-4dc4-a681-30496e1fcd64"),
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("72ee1970-3adb-42b3-8383-189e3a47b15a"),
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("14939ece-7c0c-4bc9-a6a8-5604925f3df6"),
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = new Guid("eea2d7ff-ec84-41f5-bab6-5c07fe14fea5"),
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = new Guid("658e69a3-d19f-4928-ad38-4a9749377fa0"),
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("8e5b599d-20c0-40d5-bd6c-bbb399c9cc5d"),
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = new Guid("9d83fe43-8711-4d43-a057-606d0041655f"),
                            Name = "Caribbean Netherlands"
                        },
                        new
                        {
                            Id = new Guid("22f45b8a-c769-4ce4-8bb4-f6a416dc2240"),
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = new Guid("fb7fc57d-b913-404c-bd21-c4eb6f7d0ec8"),
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = new Guid("1718ff7c-a4f3-4882-9c25-f8819608b1c5"),
                            Name = "Chad"
                        },
                        new
                        {
                            Id = new Guid("843387a2-766a-4d4d-a0ea-7ff144b98989"),
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("73ad557e-994d-4e96-992e-c6320dc08892"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("864f39d6-ba28-42c4-9016-4cf29878945e"),
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = new Guid("c7824a68-83d3-4008-a8c3-27d1b94c5c1d"),
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = new Guid("fe06410b-4872-4891-a5d0-630fba46cd9f"),
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("6cd1264e-3b9f-42a6-86cc-2b9cfd09221d"),
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = new Guid("56a8ac24-4dbe-439f-b6a8-159589b9a612"),
                            Name = "Congo - Brazzaville"
                        },
                        new
                        {
                            Id = new Guid("2dad4692-0ce7-4c4e-a3dd-f4dd39ac541e"),
                            Name = "Congo - Kinshasa"
                        },
                        new
                        {
                            Id = new Guid("2c36bcac-760a-4e59-8927-420f241ac14a"),
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = new Guid("326495bb-1488-48f3-8c18-2cd8cbd3c98d"),
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("04e64c6d-e920-420d-b47c-c7c4dc2be4fb"),
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("92543a15-0e86-4a8e-8543-82f7a0c19a1b"),
                            Name = "Curaçao"
                        },
                        new
                        {
                            Id = new Guid("4a12724f-c780-48d5-a100-052e74475a85"),
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = new Guid("d7cefdb1-a4af-4dcb-8df8-84a8b071fc90"),
                            Name = "Czechia"
                        },
                        new
                        {
                            Id = new Guid("9082958f-9303-43f8-8a78-16ae378770fd"),
                            Name = "Côte d’Ivoire"
                        },
                        new
                        {
                            Id = new Guid("c4f73e5e-9ee6-47ff-8aaf-2c27b174e8b4"),
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("425cd588-aa02-4f0a-b358-5438dd1ac1f4"),
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("cbfd849c-17a0-4a7f-82c3-6720afb2c64e"),
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("d425b3f0-468e-49cf-bda2-69b3577a1728"),
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = new Guid("ac6ea3cf-784d-4d30-8549-a13c11626a27"),
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("350db462-2695-4f10-9e94-83e60c474a90"),
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("f23e873e-f708-43fd-85c3-968730dc4204"),
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("2affa3c6-572e-40df-9b6a-0052e47e82c9"),
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = new Guid("1f6fbbca-48bd-44aa-8ff2-94c2068fd445"),
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("1ee005a5-0734-4560-b175-b903c40b5a5e"),
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("d9585f81-5726-49c4-9802-4e3c37b3050f"),
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = new Guid("01eeb568-aefb-4b38-b20a-8a5d9e5f2e3d"),
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = new Guid("b5609d6f-b7ec-4122-977e-0ee33f4cc4f2"),
                            Name = "Falkland Islands"
                        },
                        new
                        {
                            Id = new Guid("bb72733a-051f-4db7-a40a-f87492bd582d"),
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = new Guid("e336d93e-9be7-4653-b5ae-9ed879eb2024"),
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("623c9753-eb23-4483-99b3-cc935aa620cf"),
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("b6b8dcfe-ad7a-494b-ab33-03b84f8521df"),
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("65d0335a-d227-448b-bee4-68b185823223"),
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = new Guid("bc9ad3f3-01f4-4978-9a80-3506eae18472"),
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = new Guid("f0f872c2-b6cb-4bd1-9f83-20c16f5667dc"),
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = new Guid("cb247e3e-5453-40e1-9cee-7a93031f6a35"),
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = new Guid("a84bda95-b72b-4d6f-a1be-26b8b133e594"),
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("10c3b512-5192-4ce2-8ff9-9c1da9b0e4f5"),
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("3ce166b2-80cf-43da-87c2-8b5c2d5ee9fc"),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("d2271384-059f-4e6e-be1e-2db6d6681f06"),
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("7beb3843-a7ca-4b68-b2d3-c910d19435ab"),
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = new Guid("b17a5cba-686d-4b7c-ac6c-f10fd710ce61"),
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("fa45fc44-3a86-4180-b8c4-352c8a403617"),
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = new Guid("34fdf93b-fe57-4d19-b36b-e71cf3752f9c"),
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = new Guid("4e5fe40c-d3a2-4c97-aa8b-76fb14fce5b9"),
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = new Guid("086ed320-f77e-450e-b850-eeb5c16f338b"),
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("6c91b04f-28e0-4bee-8a21-674ce7c7c4a3"),
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = new Guid("655b8d47-7d7b-411c-bebe-a27358a93dfe"),
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("50653a27-905c-4e63-add2-bfd2e632abd8"),
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = new Guid("de971f98-d3c7-4fed-b821-02f22155f32c"),
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("af5800c3-016d-4ed3-aa02-667b0650c583"),
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = new Guid("d56e8115-c228-4819-98ba-84012d378520"),
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("f956976d-f54a-40c7-9c29-4761b402349b"),
                            Name = "Hong Kong SAR"
                        },
                        new
                        {
                            Id = new Guid("11164fc8-0baf-48a9-a5dd-c6817d7f9bfe"),
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("3153e0d5-7247-433e-9c8a-bcf341a34ee5"),
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = new Guid("905530b0-6ab7-4423-a631-c136a6f0934a"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("1005e705-3392-4b8d-8359-b89e36122735"),
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("1ba29009-b3b4-470d-a30c-c1416163489b"),
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("2d6b7160-1796-44b9-a696-e1920d93f346"),
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("56226f3e-e53d-4b07-b1c6-a03d56895653"),
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = new Guid("4acabe60-63d5-43f4-aebe-348108708544"),
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("f52faef9-5f48-4428-b642-a5c5299a37d4"),
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("7250b096-aa86-4c72-824f-00794fea6f1e"),
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("ef1eac36-31af-4b45-aa73-619d8bfd52df"),
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("7e9faabe-1a44-41d6-a06d-fc465817010b"),
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = new Guid("744f333b-127d-4aeb-9b75-841ad3ab6fed"),
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = new Guid("b10482e9-eda0-480c-b946-96b7b292a1d5"),
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = new Guid("2875fc10-9664-484c-8cf6-fffa0b1b3d7c"),
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("e93383fa-6f2d-46db-8d12-77fda4f544b0"),
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("74c53214-5c0a-4c4b-800a-e0afbc85fbf2"),
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = new Guid("f52ebc0d-0ce4-4803-b2ab-b3955405d9fb"),
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("5d965a66-fe12-4535-99f3-e7f22487f3a5"),
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = new Guid("7136b77f-186c-4cfd-a76b-cce78abf96d0"),
                            Name = "Laos"
                        },
                        new
                        {
                            Id = new Guid("78e80316-04c1-414b-be00-9ec3e8a46786"),
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = new Guid("153afaee-89f1-49b9-8fae-b113b026f2b5"),
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = new Guid("c86e16cb-1c56-4268-baab-fcf6d0201e25"),
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = new Guid("6c4af999-2222-4415-a918-6be5e68ee8db"),
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("764d816f-ac41-4ab5-a1fe-33a2c542e0ec"),
                            Name = "Libya"
                        },
                        new
                        {
                            Id = new Guid("79002fb4-f346-4df6-a690-2d0fdd8e9689"),
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("d7077202-41d8-451d-aff5-e926a27970af"),
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = new Guid("a3bb40f0-faf1-4a73-bc62-a3df2555c427"),
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = new Guid("2bfdde11-401b-41a9-8af8-e2476f3c8944"),
                            Name = "Macao SAR"
                        },
                        new
                        {
                            Id = new Guid("c1e0f5e6-1c11-491e-a7d4-a6caed4d25b6"),
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("1f1b021b-605a-4ab4-bdf0-bfeeda8462b0"),
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("513e03ec-fd15-4049-98eb-78b80f2840c1"),
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = new Guid("fb2c9da3-7fef-47f5-871c-8f1705c7d6f3"),
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = new Guid("04e2c1f3-1c6b-4fa6-837f-0beadde2fc7d"),
                            Name = "Mali"
                        },
                        new
                        {
                            Id = new Guid("b0e323ee-2960-4ac3-8d2f-fc740bd36295"),
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("1dc6c70e-e12c-47b2-902b-b9ffa17dce4a"),
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = new Guid("a3c99401-70c0-434c-8177-49e1b613304b"),
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("ec75157b-12c3-45bb-ae4b-cf122d045fe9"),
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = new Guid("e3b212d9-8ca3-4cd3-88c7-a9de3dfe22f2"),
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = new Guid("b8473c64-c52d-46fb-ad2a-88a8bf751616"),
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("95c8aaca-1eb5-4c18-aad8-6a663dc8daba"),
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = new Guid("5547745c-cef8-41e1-bc35-93e8d6fe33ba"),
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("2f11c0e0-3c57-4ea6-970f-7ba9716904e3"),
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("6a377230-e9f2-496a-8252-d0172ab294b7"),
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("a44c5f79-6da2-4e18-af8b-f59a95cf35f2"),
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = new Guid("5238c4c3-f231-4c82-b99f-aae3f391b29d"),
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = new Guid("ee30388a-4f3e-4692-a1b4-4204e84d9530"),
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("5d8b7189-2858-4661-964e-d66d91ffbb0c"),
                            Name = "Myanmar (Burma)"
                        },
                        new
                        {
                            Id = new Guid("a0c38375-f691-44eb-9ee2-f0a1a3d16530"),
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("0d8b7d79-da31-4952-9aad-ac551a59d260"),
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("5fd2d806-f721-474c-b244-af4a560d4d9b"),
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("df4ef662-5ea5-45cd-b431-6e2182ac1980"),
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("cd00e532-87cf-4b1c-8468-c7bd91e9457b"),
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = new Guid("d1159ea5-e537-48df-ab4e-393a7f39d652"),
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("b8af39a6-ad3e-413f-af6f-e8288b17b16d"),
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("39db7626-7f48-4136-924c-05643c9969c9"),
                            Name = "Niger"
                        },
                        new
                        {
                            Id = new Guid("8a78592a-739b-45fd-a5ae-9d2d55fcf13a"),
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("b6560646-e7ea-459a-9718-465ae1ea7953"),
                            Name = "Niue"
                        },
                        new
                        {
                            Id = new Guid("f396183d-d234-480e-9b67-323fd21f4433"),
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = new Guid("79925a6f-916d-4ae5-8613-a61ab8f3d0d1"),
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = new Guid("3e061180-aff9-4d03-b0d4-8b23bf29a053"),
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("110b637d-390f-4147-a939-fb8151a57402"),
                            Name = "Oman"
                        },
                        new
                        {
                            Id = new Guid("3059da70-9cd8-4e2d-98e3-092fbe4754d2"),
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("b049386f-affe-4367-8aea-152d3d3b1979"),
                            Name = "Palestinian Territories"
                        },
                        new
                        {
                            Id = new Guid("7fdeb9e0-9557-4229-903f-166788dd0199"),
                            Name = "Panama"
                        },
                        new
                        {
                            Id = new Guid("a0eca863-6de1-4627-8c17-00f01886ede2"),
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = new Guid("a9a5d9c4-e3cf-49e0-8971-873596875d08"),
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("f22aad98-b8c5-4640-9a49-327565d1cfcc"),
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("741e1a2d-70dc-4600-a602-c63d49621645"),
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("69f20c84-a8f5-42fe-a6b4-1e1746d5f97b"),
                            Name = "Pitcairn Islands"
                        },
                        new
                        {
                            Id = new Guid("bafc1200-16e8-414b-ba35-10f39b80b24a"),
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("39654c0b-4e6d-437f-97fa-aa55d74ea710"),
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("3620b7f9-dbcc-405d-87bb-a15cae7f2ee4"),
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("4895c19c-4ba9-4347-a7f9-585ba8d515ed"),
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = new Guid("fef0d8fa-1ade-41f3-bff7-b2cb216fe6eb"),
                            Name = "Romania"
                        },
                        new
                        {
                            Id = new Guid("d3876397-54f8-47c4-920b-06f2f2edb6ab"),
                            Name = "Russia"
                        },
                        new
                        {
                            Id = new Guid("5fd54e05-d1ad-4fab-8cde-ea87360db83e"),
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = new Guid("7befd5c6-c616-4d61-8cc7-237d8db1121a"),
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("01e78487-fc58-4a12-b18b-24262db2610b"),
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("f498f09e-6ed9-496d-818e-0acb9e526deb"),
                            Name = "São Tomé & Príncipe"
                        },
                        new
                        {
                            Id = new Guid("ec5280ec-295f-469a-a374-39c66de930e3"),
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("ee8c90fe-281c-409e-abbc-79e8e943bb4e"),
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("2dfda921-f9a2-4449-aa07-72d0ffe8c463"),
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("a7069e9c-9045-413c-80f8-b73f44abd748"),
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("ae0744f4-dafe-4c08-845f-05723facb48a"),
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = new Guid("d00dbd74-9f7a-466b-9cf0-efdeb8c080ce"),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("55b828aa-987f-4e70-a6bc-490439d60822"),
                            Name = "Sint Maarten"
                        },
                        new
                        {
                            Id = new Guid("9f72fbbe-967e-4096-a7b9-7677733be443"),
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = new Guid("0337db63-6498-4cbf-aac9-b5c624244afe"),
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = new Guid("3d64054d-5d3a-4a15-9790-4bb72e6eba2b"),
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = new Guid("b65726ea-b109-4355-ba49-e1c4f2753177"),
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("531d43e4-7c77-44df-b209-6a54c13bee86"),
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("8c3628e0-28d2-4321-a17a-a58ce86fb010"),
                            Name = "South Georgia & South Sandwich Islands"
                        },
                        new
                        {
                            Id = new Guid("682d0f73-cd6c-4df7-a73b-beda07575d63"),
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = new Guid("42473a18-e781-4787-aa66-b438410d2305"),
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = new Guid("51d4ac33-744c-4baf-b321-6a5327f24b3c"),
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("54f06d3c-ee25-4489-88a9-9f9fd84b9638"),
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("d1672445-f6bf-42b5-acae-86ffdd1377df"),
                            Name = "St. Barthélemy"
                        },
                        new
                        {
                            Id = new Guid("4f19c870-06d4-4333-9881-c54bd1b70296"),
                            Name = "St. Helena"
                        },
                        new
                        {
                            Id = new Guid("7eee547e-32da-41fe-bb83-082cb9867a39"),
                            Name = "St. Kitts & Nevis"
                        },
                        new
                        {
                            Id = new Guid("ae824a9f-86a9-46ba-8788-27c00203acfd"),
                            Name = "St. Lucia"
                        },
                        new
                        {
                            Id = new Guid("e1fd2f53-66cf-4883-b0e8-03967178786a"),
                            Name = "St. Martin"
                        },
                        new
                        {
                            Id = new Guid("bd7ab324-f34d-4586-a813-bc8735a1abd2"),
                            Name = "St. Pierre & Miquelon"
                        },
                        new
                        {
                            Id = new Guid("552d89ef-cd8e-4360-9487-17c5fad2416b"),
                            Name = "St. Vincent & Grenadines"
                        },
                        new
                        {
                            Id = new Guid("d1835df3-09be-4812-9915-91c0a4dc7719"),
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = new Guid("73a9f36b-8a7c-47f5-9e70-61004c0a52ca"),
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = new Guid("6a96d017-4298-4560-a928-0677c7dee3b9"),
                            Name = "Svalbard & Jan Mayen"
                        },
                        new
                        {
                            Id = new Guid("4294d008-5164-480c-92e0-552a3c19a8e2"),
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("245339c1-2862-44ab-8db7-b9a5794049c6"),
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("9eb63314-290f-4904-9195-4225bc6f9561"),
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = new Guid("b3861c75-7836-4f14-95f9-c02266f067f1"),
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = new Guid("c1ec5f52-e491-48a2-9ba1-49e8ee783247"),
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = new Guid("4334eecf-da69-4c66-a1b9-9718c720d7e1"),
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("9c709236-7036-4594-b3c9-e9ea0bce3fba"),
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = new Guid("be049a72-8e9b-46d0-9148-f1969b5add30"),
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("bfd6955f-a367-4bfd-a5ab-85bfe0de4a13"),
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = new Guid("edd5ae24-c772-4e12-b6b6-58c80411862a"),
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("75032198-137a-4a58-bf97-58ab690deaa5"),
                            Name = "Trinidad & Tobago"
                        },
                        new
                        {
                            Id = new Guid("8f0312a0-e65b-4011-82c2-4e4612eb4214"),
                            Name = "Tristan da Cunha"
                        },
                        new
                        {
                            Id = new Guid("66113555-5570-40a9-b091-578439a406fb"),
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = new Guid("e30db5e6-a417-4864-93fa-16c9c8a3db86"),
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("7c5e8b8b-020a-4c2e-809e-41a39da4766d"),
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = new Guid("00e3f5c6-93d4-4d0f-943a-c3ee2f6297b1"),
                            Name = "Turks & Caicos Islands"
                        },
                        new
                        {
                            Id = new Guid("8b44e713-dc6f-4573-8a16-8e916a5f6119"),
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("46310607-8bc6-4b45-8b17-6e25c2fa9e6c"),
                            Name = "U.S. Outlying Islands"
                        },
                        new
                        {
                            Id = new Guid("e540d79b-ed23-4e3f-8f9d-c5212c6029f7"),
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("25aa079d-d1d7-4834-8ab2-95c99e736612"),
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("d498cbec-9982-47a3-aaab-b3195064527c"),
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = new Guid("b1d2cbc1-bfb5-47ae-9071-a71ee90207b2"),
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("3fe67f40-f2c1-40fa-bfa6-0a76dffb714f"),
                            Name = "United States"
                        },
                        new
                        {
                            Id = new Guid("da41ac07-a2a7-40f6-aeb6-953ef305180e"),
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("619c10a0-89b5-421a-81c0-f2078291c86a"),
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = new Guid("871c70a0-88d7-4b14-a8f3-6bbfd384c796"),
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("4c354fc6-50b1-4f83-a8b3-e42412ab490d"),
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = new Guid("54895fed-3e01-4440-b0d2-74c1f89f7206"),
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("0891ebf0-baf1-4df9-b700-eca150795067"),
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = new Guid("b792e273-16ef-4411-bf0e-dd1535b379d3"),
                            Name = "Wallis & Futuna"
                        },
                        new
                        {
                            Id = new Guid("2bbcb8cb-7a5a-44ef-823d-65f7f85b6b47"),
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = new Guid("0e0112ac-d35b-4175-9dbc-443626034c28"),
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("7254a6bf-9645-4c35-b1fc-361c5732145b"),
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("efc6df51-1330-4bb4-b83c-b9dce65e7332"),
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("DotnetStore.Models.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("DotnetStore.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DotnetStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DotnetStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("DotnetStore.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotnetStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DotnetStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
